//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfipSueldo
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha_de_pago { get; set; }
        public string Período { get; set; }
        public Nullable<int> Horas_trabajadas { get; set; }
        public Nullable<int> Horas_extras { get; set; }
        public Nullable<int> Antiguedad { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<double> S_A_C { get; set; }
        public Nullable<double> Conceptos_vaios { get; set; }
        public Nullable<double> Total_Remunerado { get; set; }
        public Nullable<long> Número_de_VEP { get; set; }
        public byte[] Comprobante_Recibo_Sueldo { get; set; }
        public string Nota { get; set; }
    }
}
