//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosMensuales
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha_de_carga { get; set; }
        public string Mes { get; set; }
        public string Nombre_Tipo { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public byte[] Comprobantes { get; set; }
        public string NombreReal { get; set; }
    }
}
